### ISSUE TITLE
Nuxt.js ?

### ISSUE THREAD

**Issue by Atinux** [cosmicjs/next.js-website#1]
Hi!

Great work with CosmicJS 🔥 

I would like to know if you guys are interested to port this example to Nuxt.js as well?

I would open the Vue.js community as well to CosmicJS!

**Comment by tonyspiro** [comment]
Hey @Atinux, sure!  I would be interested in adding this, but I'm not as familiar with Vue as I am with React.  Do you know anyone that would want to do it?

**Comment by Atinux** [comment]
Sure! I can work on it with my brother @alexchopin, I'll keep you updated!

If you are familiar with React, Vue will be really easy for you 😄

**Comment by tonyspiro** [comment]
Thanks @Atinux!  Looking forward to checking it out.  Let me know if you have any questions about Cosmic! 🚀

**Comment by Atinux** [comment]
Hey @tonyspiro 

I finished the repository with Nuxt.js, I let you check it: https://github.com/Atinux/cosmic-nuxt

Online demo: https://cosmicjs.nuxtjs.org

**Comment by tonyspiro** [comment]
@Atinux wow, that was quick! 🚀  It looks great amazing! 😃
